### ISSUE TITLE
aur package version

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [gauteh/abunchoftags#5]
[AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=abunchoftags) shows an old commit hash.

**Comment by gauteh** [comment]
Hi Aurélien,

the AUR package is a git package and the version number doesn't mean
much. Anyway, the AUR repository is included as a submodule in the main
repository - so whenever I update the version in Arch it will become out
of date once I commit the changes.

Regards, Gaute

**Comment by make-github-pseudonymous-again** [comment]
Ok I see... I installed it via yaourt and it forces to reinstall abunchoftags everytime I want to `yaourt -Syyu` because the versions do not match.

**Comment by gauteh** [comment]
Aurélien Ooms writes on august 31, 2016 23:24:

> Ok I see... I installed it via yaourt and it forces to reinstall abunchoftags everytime I want to `yaourt -Syyu` because the versions do not match.

That is probably because it is a devel package, I don't think it would
make a difference.

**Comment by make-github-pseudonymous-again** [comment]
Ok, thanks for the explanation!

**Comment by make-github-pseudonymous-again** [comment]
So why is it a devel package?

**Comment by gauteh** [comment]
Aurélien Ooms writes on september 7, 2016 16:52:

> So why is it a devel package?

Because there hasn't been any releases, and I don't think it is mature
enough / user-friendly enough to be released. At any rate it would not
make much difference.

The reason for the rebuilds are likely Yaourt. Another aur package
manager would probably notice that nothing has changed in the git
repository. Or you can try to configure Yaourt to have a persistent
cache.
